export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Resume } from "./Resume";
export { default as Homework } from "./Homework";
export { default as Responsive } from "./Responsive";
export { default as Theme } from "./Theme";